dir: "{{.InterfaceDir}}/mocks/"
filename: "{{ .InterfaceName | snakecase }}.go"
formatter: goimports
structname: "{{.InterfaceName}}"
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  package-name:
    config:
      all: true
      recursive: true
