// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_room.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertRoom = `-- name: InsertRoom :one
INSERT INTO rooms (code, host_player_id, status, config_json, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, code, host_player_id, status, config_json, created_at
`

type InsertRoomParams struct {
	Code         interface{}    `json:"code"`
	HostPlayerID int64          `json:"host_player_id"`
	Status       string         `json:"status"`
	ConfigJson   sql.NullString `json:"config_json"`
	CreatedAt    int64          `json:"created_at"`
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, insertRoom,
		arg.Code,
		arg.HostPlayerID,
		arg.Status,
		arg.ConfigJson,
		arg.CreatedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.HostPlayerID,
		&i.Status,
		&i.ConfigJson,
		&i.CreatedAt,
	)
	return i, err
}
