// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insert_player.sql

package sqlc

import (
	"context"
)

const insertPlayer = `-- name: InsertPlayer :one
INSERT INTO players (name, created_at)
VALUES (?, ?)
RETURNING id, name, created_at
`

type InsertPlayerParams struct {
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) InsertPlayer(ctx context.Context, arg InsertPlayerParams) (Player, error) {
	row := q.db.QueryRowContext(ctx, insertPlayer, arg.Name, arg.CreatedAt)
	var i Player
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
