// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type GooseDbVersion struct {
	ID        int64        `json:"id"`
	VersionID int64        `json:"version_id"`
	IsApplied int64        `json:"is_applied"`
	Tstamp    sql.NullTime `json:"tstamp"`
}

type Player struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

type Room struct {
	ID           int64          `json:"id"`
	Code         interface{}    `json:"code"`
	HostPlayerID int64          `json:"host_player_id"`
	Status       string         `json:"status"`
	ConfigJson   sql.NullString `json:"config_json"`
	CreatedAt    int64          `json:"created_at"`
}

type SqliteSequence struct {
	Name interface{} `json:"name"`
	Seq  interface{} `json:"seq"`
}
