// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	InsertPlayer(ctx context.Context, arg InsertPlayerParams) (Player, error)
	InsertRoom(ctx context.Context, arg InsertRoomParams) (Room, error)
}

var _ Querier = (*Queries)(nil)
